data_file = /home/cdkbs/mcbench-pw7/run/A-creating-t2-rows200/multi-core.db
port = 15541
cores = 2
placement = creating
peer_listeners = off
log_file = multi-core.log
log_dir = /home/cdkbs/mcbench-pw7/run/A-creating-t2-rows200
log_level = warn
