data_file = /home/cdkbs/mcbench-pw7/run/B-rotate-t2-r3/multi-core.db
port = 15485
cores = 2
placement = rotate
peer_listeners = on
log_file = multi-core.log
log_dir = /home/cdkbs/mcbench-pw7/run/B-rotate-t2-r3
log_level = warn
