data_file = /home/cdkbs/mcbench-pw7/run/B-rotate-t2-r3/single-core.db
port = 15484
cores = 1
placement = rotate
peer_listeners = off
log_file = single-core.log
log_dir = /home/cdkbs/mcbench-pw7/run/B-rotate-t2-r3
log_level = warn
