data_file = /home/cdkbs/mcbench-pw7/run/B-rotate-t2-r2/multi-core.db
port = 15479
cores = 2
placement = rotate
peer_listeners = on
log_file = multi-core.log
log_dir = /home/cdkbs/mcbench-pw7/run/B-rotate-t2-r2
log_level = warn
