data_file = /home/cdkbs/mcbench-pw7/run/C-rotate-t4-r1/multi-core.db
port = 15475
cores = 2
placement = rotate
peer_listeners = on
log_file = multi-core.log
log_dir = /home/cdkbs/mcbench-pw7/run/C-rotate-t4-r1
log_level = warn
