data_file = /home/cdkbs/mcbench-pw7/run/A-creating-t2-r2/multi-core.db
port = 15477
cores = 2
placement = creating
peer_listeners = off
log_file = multi-core.log
log_dir = /home/cdkbs/mcbench-pw7/run/A-creating-t2-r2
log_level = warn
