data_file = /home/cdkbs/mcbench-pw7/run/A-creating-t2-r2/single-core.db
port = 15476
cores = 1
placement = creating
peer_listeners = off
log_file = single-core.log
log_dir = /home/cdkbs/mcbench-pw7/run/A-creating-t2-r2
log_level = warn
